<?php

// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, "https://integration-api.tangocard.com/raas/v2/catalogs?verbose=true");
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "GET");


$headers = array();
$headers[] = "Accept: application/json";
$headers[] = "Authorization: Basic UUFQbGF0Zm9ybTI6YXBZUGZUNkhOT05wRFJVajNDTEdXWXQ3Z3ZJSE9OcERSVVlQZlQ2SGo=";
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close ($ch);




?>





<section class="card-tabs">
 
 

	<!-- Tab panes -->
	<div class="tab-content">
 
		
 
		<div class="tab-pane active" id="800-flowers">                            <!--  #800-flowers amazon american-express best-buy game-stop toys-r-us-->
				
				<div class="col-md-12">
					<pre>
				<?php
										//echo "<pre>"; print_r(json_decode($result)); echo "</pre>";
					foreach (json_decode($result) as $key => $value) {				
							print_r($value);
							//die();
						foreach ($value as $key1 => $value1) {
							// echo "<pre>"; print_r($value1->brandName); echo "</pre>";

							if (strpos($value1->brandName, '800-FLOWERS') !== false) {
							    
							 ?>		
										<?php
												
													$new = get_object_vars($value1->imageUrls);
													?>
										<div class="col-md-2 nopadding">
										<input  type="radio" value="<?php echo $new['200w-326ppi'];?>" name="emotion" id="all-<?php echo $value1->brandKey ; ?>" class="input-hidden choose_card" />											
											
									<label for="all-<?php echo $value1->brandKey ; ?>"><img src="<?php echo $new['200w-326ppi'];?>" ></label>
													<?php
											?>											
										</div>															
						 <?php
						 	}
						 }

						 
					}

				?>
					
			<?php
										//echo "<pre>"; print_r(json_decode($result)); echo "</pre>";
					foreach (json_decode($result) as $key => $value) {				
							
						foreach ($value as $key1 => $value1) {
							 // echo "<pre>"; print_r($value1->brandName); echo "</pre>";

							if (strpos($value1->brandName, 'Amazon') !== false) {
							    
							 ?>		<?php
												
													$new = get_object_vars($value1->imageUrls);
													?>
										
										<div class="col-md-2 nopadding">
										<input  type="radio" value="<?php echo $new['200w-326ppi'];?>" name="emotion" id="all-<?php echo $value1->brandKey ; ?>" class="input-hidden choose_card" />											
											
									<label for="all-<?php echo $value1->brandKey ; ?>"><img src="<?php echo $new['200w-326ppi'];?>" ></label>
													<?php
											?>											
										</div>															
						 <?php
						 	}
						 }

						 
					}

				?>
				<?php
										//echo "<pre>"; print_r(json_decode($result)); echo "</pre>";
					foreach (json_decode($result) as $key => $value) {				
							
						foreach ($value as $key1 => $value1) {
							  // echo "<pre>"; print_r($value1->brandName); echo "</pre>";

							if (strpos($value1->brandName, 'Best Buy') !== false) {
							    
							 ?>		<?php
												
													$new = get_object_vars($value1->imageUrls);
													?>
										
										<div class="col-md-2 nopadding">
										<input  type="radio" value="<?php echo $new['200w-326ppi'];?>" name="emotion" id="all-<?php echo $value1->brandKey ; ?>" class="input-hidden choose_card" />											
											
									<label for="all-<?php echo $value1->brandKey ; ?>"><img src="<?php echo $new['200w-326ppi'];?>" ></label>
													<?php
											?>											
										</div>															
						 <?php
						 	}
						 }

						 
					}

				?>
				</div>
</div>				


  <p class="sent-button"><input value="Next" type="button"onclick="sentbutton()" data-dismiss="modal"></p>
	</div><!-- tab-content -->
 
</section><!-- film-tabs -->
<script type="text/javascript">

jQuery('.choose_card').change(function(){
   jQuery('#choose_card').val(jQuery(this).val());

})
</script>
