<?php

// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, "https://integration-api.tangocard.com/raas/v2/catalogs?verbose=true");
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "GET");


$headers = array();
$headers[] = "Accept: application/json";
$headers[] = "Authorization: Basic UUFQbGF0Zm9ybTI6YXBZUGZUNkhOT05wRFJVajNDTEdXWXQ3Z3ZJSE9OcERSVVlQZlQ2SGo=";
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close ($ch);




?>





<section class="card-tabs">
 <!-- <section class="gif-tabs card-tabs diff1"> -->
	<?php $post_card = get_terms('post_card'); // get all the post_card ?>
 

	<!-- Tab panes -->
	<div class="tab-content">
 
		
 
		<div class="tab-pane active diff1" id="">                            <!--  #800-flowers amazon american-express best-buy game-stop toys-r-us-->
				
				<div class="col-md-12 masonry">	
				
			<?php
										//echo "<pre>"; print_r(json_decode($result)); echo "</pre>";
					foreach (json_decode($result) as $key => $value) {				
							
						foreach ($value as $key1 => $value1) {
							// echo "<pre>"; print_r($value1->brandName); echo "</pre>";
							

							if (strpos($value1->brandName, 'Amazon') !== false) {
							    
							 ?>		<?php
												
										$new = get_object_vars($value1->imageUrls);
										//echo "<pre>"; print_r($value1->brandKey); echo "</pre>";
										?>
										
										<div class="nopadding">
										<input  type="radio" value="<?php echo $new['200w-326ppi'];?>" name="choose_card" id="all-<?php echo $value1->brandKey ; ?>" class="input-hidden choose_card" />											
									<label for="all-<?php echo $value1->brandKey ; ?>"><img src="data:image/png;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=" data-src="<?php echo $new['200w-326ppi'];?>" ></label>
													<?php
											?>											
										</div>															
						 <?php
						 	}
						 }
					}

				?>
				<?php
					foreach (json_decode($result) as $key => $value) {				
							
						foreach ($value as $key1 => $value1) {
							  // echo "<pre>"; print_r($value1->brandName); echo "</pre>";

							if (strpos($value1->brandName, 'Starbucks') !== false) {
							    
							 ?>		<?php
												
													$new = get_object_vars($value1->imageUrls);
													?>
										
										<div class="nopadding">
										<input  type="radio" value="<?php echo $new['200w-326ppi'];?>" name="choose_card" id="all-<?php echo $value1->brandKey ; ?>" class="input-hidden choose_card" />											
											
									<label for="all-<?php echo $value1->brandKey ; ?>">
									<img src="data:image/png;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=" data-src="<?php echo $new['200w-326ppi'];?>" >
									</label>
													<?php
											?>											
										</div>															
						 <?php
						 	}
						 }

						 
					}

				?>
				</div>
				<div class="col-md-12 masonry">	
				<?php
										//echo "<pre>"; print_r(json_decode($result)); echo "</pre>";
					foreach (json_decode($result) as $key => $value) {				
							
						foreach ($value as $key1 => $value1) {
							// echo "<pre>"; print_r($value1->brandName); echo "</pre>";
							

							if (strpos($value1->brandName, 'GameStop') !== false) {
							    
							 ?>		<?php
												
										$new = get_object_vars($value1->imageUrls);
										//echo "<pre>"; print_r($value1->brandKey); echo "</pre>";
										?>
										
										<div class="nopadding">
										<input  type="radio" value="<?php echo $new['200w-326ppi'];?>" name="choose_card" id="all-<?php echo $value1->brandKey ; ?>" class="input-hidden choose_card" />											
									<label for="all-<?php echo $value1->brandKey ; ?>"><img src="data:image/png;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=" data-src="<?php echo $new['200w-326ppi'];?>" ></label>
													<?php
											?>											
										</div>															
						 <?php
						 	}
						 }
					}

				?>
				<?php
										//echo "<pre>"; print_r(json_decode($result)); echo "</pre>";
					foreach (json_decode($result) as $key => $value) {				
							
						foreach ($value as $key1 => $value1) {
							// echo "<pre>"; print_r($value1->brandName); echo "</pre>";
							

							if (strpos($value1->brandName, 'Best Buy') !== false) {
							    
							 ?>		<?php
												
										$new = get_object_vars($value1->imageUrls);
										//echo "<pre>"; print_r($value1->brandKey); echo "</pre>";
										?>
										
										<div class="nopadding">
										<input  type="radio" value="<?php echo $new['200w-326ppi'];?>" name="choose_card" id="all-<?php echo $value1->brandKey ; ?>" class="input-hidden choose_card" />											
									<label for="all-<?php echo $value1->brandKey ; ?>"><img src="data:image/png;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=" data-src="<?php echo $new['200w-326ppi'];?>" ></label>
													<?php
											?>											
										</div>															
						 <?php
						 	}
						 }
					}

				?>
				<?php
					foreach (json_decode($result) as $key => $value) {				
							
						foreach ($value as $key1 => $value1) {
							  // echo "<pre>"; print_r($value1->brandName); echo "</pre>";

							if (strpos($value1->brandName, 'The Home Depot®') !== false) {
							    
							 ?>		<?php
												
													$new = get_object_vars($value1->imageUrls);
													?>
										
										<div class="nopadding">
										<input  type="radio" value="<?php echo $new['200w-326ppi'];?>" name="choose_card" id="all-<?php echo $value1->brandKey ; ?>" class="input-hidden choose_card" />											
											
									<label for="all-<?php echo $value1->brandKey ; ?>"><img src="data:image/png;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=" data-src="<?php echo $new['200w-326ppi'];?>" ></label>
													<?php
											?>											
										</div>															
						 <?php
						 	}
						 }

						 
					}

				?>
				<?php
					foreach (json_decode($result) as $key => $value) {				
							
						foreach ($value as $key1 => $value1) {
							  // echo "<pre>"; print_r($value1->brandName); echo "</pre>";

							if (strpos($value1->brandName, 'Gap') !== false) {
							    
							 ?>		<?php
												
													$new = get_object_vars($value1->imageUrls);
													?>
										
										<div class="nopadding">
										<input  type="radio" value="<?php echo $new['200w-326ppi'];?>" name="choose_card" id="all-<?php echo $value1->brandKey ; ?>" class="input-hidden choose_card" />											
											
									<label for="all-<?php echo $value1->brandKey ; ?>"><img src="data:image/png;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=" data-src="<?php echo $new['200w-326ppi'];?>" ></label>
													<?php
											?>											
										</div>															
						 <?php
						 	}
						 }

						 
					}

				?>

				</div>

			
				<div class="col-md-12 masonry">	
					<?php
					foreach (json_decode($result) as $key => $value) {				
							
						foreach ($value as $key1 => $value1) {
							  // echo "<pre>"; print_r($value1->brandName); echo "</pre>";

							if (strpos($value1->brandName, 'Target') !== false) {
							    
							 ?>		<?php
												
													$new = get_object_vars($value1->imageUrls);
													?>
										
										<div class="nopadding">
										<input  type="radio" value="<?php echo $new['200w-326ppi'];?>" name="choose_card" id="all-<?php echo $value1->brandKey ; ?>" class="input-hidden choose_card" />											
											
									<label for="all-<?php echo $value1->brandKey ; ?>"><img src="data:image/png;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs="  data-src="<?php echo $new['200w-326ppi'];?>" ></label>
													<?php
											?>											
										</div>															
						 <?php
						 	}
						 }

						 
					}

				?>
				
				</div>
				<div class="col-md-12 masonry">	

				<?php
					foreach (json_decode($result) as $key => $value) {				
							
						foreach ($value as $key1 => $value1) {
							  // echo "<pre>"; print_r($value1->brandName); echo "</pre>";

							if (strpos($value1->brandName, 'Barnes & Noble') !== false) {
							    
							 ?>		<?php
												
													$new = get_object_vars($value1->imageUrls);
													?>
										
										<div class="nopadding">
										<input  type="radio" value="<?php echo $new['200w-326ppi'];?>" name="choose_card" id="all-<?php echo $value1->brandKey ; ?>" class="input-hidden choose_card" />											
											
									<label for="all-<?php echo $value1->brandKey ; ?>"><img src="data:image/png;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=" data-src="<?php echo $new['200w-326ppi'];?>" ></label>
													<?php
											?>											
										</div>															
						 <?php
						 	}
						 }

						 
					}

				?>

				<?php
					foreach (json_decode($result) as $key => $value) {				
							
						foreach ($value as $key1 => $value1) {
							  // echo "<pre>"; print_r($value1->brandName); echo "</pre>";

							if (strpos($value1->brandName, 'Nordstrom') !== false) {
							    
							 ?>		<?php
												
													$new = get_object_vars($value1->imageUrls);
													?>
										
										<div class="nopadding">
										<input  type="radio" value="<?php echo $new['200w-326ppi'];?>" name="choose_card" id="all-<?php echo $value1->brandKey ; ?>" class="input-hidden choose_card" />											
											
									<label for="all-<?php echo $value1->brandKey ; ?>"><img src="data:image/png;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=" data-src="<?php echo $new['200w-326ppi'];?>" ></label>
													<?php
											?>											
										</div>															
						 <?php
						 	}
						 }

						 
					}

				?>
				
			</div>

			<div class="col-md-12 masonry">	
				<?php
					foreach (json_decode($result) as $key => $value) {				
							
						foreach ($value as $key1 => $value1) {
							  // echo "<pre>"; print_r($value1->brandName); echo "</pre>";

							if (strpos($value1->brandName, 'L.L.Bean') !== false) {
							    
							 ?>		<?php
												
													$new = get_object_vars($value1->imageUrls);
													?>
										
										<div class="nopadding">
										<input  type="radio" value="<?php echo $new['200w-326ppi'];?>" name="choose_card" id="all-<?php echo $value1->brandKey ; ?>" class="input-hidden choose_card" />											
											
									<label for="all-<?php echo $value1->brandKey ; ?>"><img src="data:image/png;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=" data-src="<?php echo $new['200w-326ppi'];?>" ></label>
													<?php
											?>											
										</div>															
						 <?php
						 	}
						 }

						 
					}

				?>
				<?php
					foreach (json_decode($result) as $key => $value) {				
							
						foreach ($value as $key1 => $value1) {
							  // echo "<pre>"; print_r($value1->brandName); echo "</pre>";

							if (strpos($value1->brandName, 'Pottery Barn®') !== false) {
							    
							 ?>		<?php
												
													$new = get_object_vars($value1->imageUrls);
													?>
										
										<div class="nopadding">
										<input  type="radio" value="<?php echo $new['200w-326ppi'];?>" name="choose_card" id="all-<?php echo $value1->brandKey ; ?>" class="input-hidden choose_card" />											
											
									<label for="all-<?php echo $value1->brandKey ; ?>"><img src="data:image/png;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=" data-src="<?php echo $new['200w-326ppi'];?>" ></label>
													<?php
											?>											
										</div>															
						 <?php
						 	}
						 }

						 
					}

				?>
			</div>


				


</div>				


  <!--<p class="sent-button"><input value="Next" type="button"onclick="sentbutton()" data-dismiss="modal" class="submit btn btn-info"></p>-->
  
	</div><!-- tab-content -->
 <p class="sent-button">
  <!--<input value="Next" type="button" onclick="sentbutton()" data-dismiss="modal" class="submit btn btn-info">-->
  <a href="#myModal21" role="button" onclick="sentbutton()" data-dismiss="modal" class="submit btn btn-info" data-toggle="modal">Next</a>
  </p>
</section><!-- film-tabs -->
<script type="text/javascript">

jQuery('.choose_card').change(function(){
   jQuery('#choose_card').val(jQuery(this).val());

})
</script>
<script>
function init() {
var imgDefer = document.getElementsByTagName('img');
for (var i=0; i<imgDefer.length; i++) {
if(imgDefer[i].getAttribute('data-src')) {
imgDefer[i].setAttribute('src',imgDefer[i].getAttribute('data-src'));
} } }
window.onload = init;
</script>
